Description: CloudFormation template for creating an ec2 instance
Parameters:
  KeyName:
    Description: Key Pair name
    Type: 'AWS::EC2::KeyPair::KeyName'
    Default: JenkinKP
  VPC:
    Type: 'AWS::EC2::VPC::Id'
    Default: vpc-7c242614
  Subnet:
    Type: 'AWS::EC2::Subnet::Id'
    Default: subnet-4620b90a
  InstanceType:
    Description: Select one of the possible instance types
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
  SecurityGroup:
    Type: 'AWS::EC2::SecurityGroup::Id'
    Default: sg-0dd631b82dc367686
    AllowedValues:
      - sg-0dd631b82dc367686
      - sg-0ac888e41706b56e8
      - sg-021757b5e1320994f
Resources:
  Server:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: ami-0a74bfeb190bd404f
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      SecurityGroupIds:
        - !Ref SecurityGroup
      SubnetId: !Ref Subnet
Outputs:
  PublicName:
    Value: !GetAtt 
      - Server
      - PublicDnsName
    Description: Public name (connect via SSH)
