--- 
Description: "CloudFormation template for creating an ec2 instance"
Outputs: 
  PublicName: 
    Description: "Public name (connect via SSH)"
    Value: 
      ? "Fn::GetAtt"
      : 
        - Server
        - PublicDnsName
Parameters: 
  InstanceType: 
    AllowedValues: 
      - t2.micro
      - t2.small
      - t2.medium
    Default: t2.micro
    Description: "Select one of the possible instance types"
    Type: String
  KeyName: 
    Default: xxx-xxx
    Description: "Key Pair name"
    Type: "AWS::EC2::KeyPair::KeyName"
  SecurityGroup: 
    AllowedValues: 
      - sg-xxxxx
      - sg-yyy
      - sg-zzz
    Default: givesecuritygroupid
    Type: "AWS::EC2::SecurityGroup::Id"
  Subnet: 
    Default: givesubnetid
    Type: "AWS::EC2::Subnet::Id"
  VPC: 
    Default: givevpcid
    Type: "AWS::EC2::VPC::Id"
Resources: 
  Server: 
    Properties: 
      ImageId: ami-098789xxxxxxxxx
      InstanceType: 
        Ref: InstanceType
      KeyName: 
        Ref: KeyName
      SecurityGroupIds: 
        - 
          Ref: SecurityGroup
      SubnetId: 
        Ref: Subnet
    Type: "AWS::EC2::Instance"